wait(0.01)
loadstring(game:HttpGet("https://raw.githubusercontent.com/Aisen11394/NORMESP1/main/.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Aisen11394/NORMESP2/main/.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Aisen11394/NORMESP3/main/.lua"))()
end)
